name: CI local

on: [push]

env:
    DB_HOST: 127.0.0.1
    DB_USER: root
    DB_PASSWORD: root
    DB_NAME: todolist_db
    PORT: 3000
    NODE_ENV: test

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Setup node 24
              uses: actions/setup-node@v4
              with:
                node-version: "24"
                cache: "npm"

            - name: install dependencies
              run: npm ci

            - name: Test
              run: npm run test

            - name : Upload coverage artifact
              uses: actions/upload-artifact@v4
              with:
                name: coverage-report
                path: coverage/
                retention-days: 7
